export default {
  getConfig: 'https://us-central1-jellytree-3cb33.cloudfunctions.net/getConfig',
  setCartProduct: 'https://us-central1-jellytree-3cb33.cloudfunctions.net/setCartProduct',
  getProduct: 'https://us-central1-jellytree-3cb33.cloudfunctions.net/getProduct',
  listProducts: 'https://us-central1-jellytree-3cb33.cloudfunctions.net/listProducts',
  listCartProducts: 'https://us-central1-jellytree-3cb33.cloudfunctions.net/listCartProducts',
  deleteCartProduct: 'https://us-central1-jellytree-3cb33.cloudfunctions.net/deleteCartProduct',
  updateCartProductQty: 'https://us-central1-jellytree-3cb33.cloudfunctions.net/updateCartProductQty',
  moveToSaveForLater: 'https://us-central1-jellytree-3cb33.cloudfunctions.net/moveToSaveForLater',
  batchMoveToSaveForLater: 'https://us-central1-jellytree-3cb33.cloudfunctions.net/batchMoveToSaveForLater',
  listSaveForLaterProducts: 'https://us-central1-jellytree-3cb33.cloudfunctions.net/listSaveForLaterProducts',
  deleteSaveForLaterProduct: 'https://us-central1-jellytree-3cb33.cloudfunctions.net/deleteSaveForLaterProduct',
  moveToCart: 'https://us-central1-jellytree-3cb33.cloudfunctions.net/moveToCart',
  setUser: 'https://us-central1-jellytree-3cb33.cloudfunctions.net/setUser',
}